version: '3'

services:
  groupsignature:
    build:
      context: ./groupsignatures/server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./groupsignatures/server:/root/groupsigserver
