@startuml AddOffer
actor Prosumer
participant GroupSignature
participant CableCompany #LightYellow
participant Market #LightYellow
participant SmartMeter #LightYellow

skinparam dpi 400

autonumber

Prosumer -> GroupSignature ++: sign(offer, nonce)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: addOffer(offer, signature, nonce, ots, nextOtsHash)
Market -> Market: isNonceUsed(nonce)
alt !nonces.has(nonce)
Market -> CableCompany ++: isRegistered(smartMeter)
CableCompany --> Market --: SmartMeter registered

Market -> SmartMeter ++: subtractCharge(amount, ots, nextOtsHash, smAddress)
alt subtractbattery ok
SmartMeter --> Market --: OK
Market -> Market: addOffer
Market --> Prosumer: Offer created!
end 
else
Market --> Prosumer --: Offer not created
end

@enduml
