@startuml AddOffer
actor Prosumer
actor SmartMeter
participant SmartMeterContract #LightYellow
participant GroupSignature
participant Market #LightYellow
participant CableCompany #LightYellow

skinparam dpi 400

autonumber

Prosumer -> GroupSignature ++: sign(offer, nonce)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: addOffer(offer, signature, nonce, ots, nextOtsHash)
Market -> Market: isNonceUsed(nonce)
alt !nonces.has(nonce)
Market -> CableCompany ++: isRegistered(smartMeter)
CableCompany --> Market --: SmartMeter registered

Market -> SmartMeterContract ++: subtractBatteryCharge(amount, ots, nextOtsHash, smAddress)
alt subtractbattery ok
SmartMeterContract --> Market --: OK
Market -> Market: addOffer
Market --> Prosumer: Offer created!
end 
else
Market --> Prosumer --: Offer not created
end

@enduml
