@startuml BuyOffer
actor Prosumer
participant GroupSignature
participant Market #LightYellow

skinparam dpi 300

autonumber

Prosumer -> GroupSignature ++: sign(offer)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: buyOffer(id, signature)
note over Market #WhiteSmoke
offer.expirationTime > now()
owner != buyer
end note
Market -> Market: pendingOffers.add(offer)
Market --> Prosumer: Offer bought

@enduml