@startuml BuyOffer
actor Prosumer
actor DSO
participant GroupSignature
participant Market #LightYellow
participant SmartMeter #LightYellow
participant Events #LightYellow 

skinparam dpi 300

autonumber

Prosumer -> GroupSignature ++: sign(offer)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: buyOffer(id, signature)
alt offer.expirationTime > now() && owner != buyer
Market -> Market: pendingOffers.add(offer)
...Sometime later...
DSO -> Market: getPendingOffers
Market --> DSO: pendingOffers
DSO -> Market: validateOffers(indicies)
loop indicies
alt indicies[i] = false
Market -> SmartMeter ++: returnReservedBatteryCharge(address, amount)
SmartMeter --> Market --: OK
else
Market -> Events: emit new contract(pendingOffer[i])
end
end

@enduml