@startuml BuyOffer
actor DSO
participant Market #LightYellow
participant SmartMeter #LightYellow
participant Events #LightYellow 

skinparam dpi 300

autonumber

DSO -> Market ++: getPendingOffers
Market --> DSO --: pendingOffers
DSO -> Market ++: validateOffers(offers)
loop offers
alt offers[i] = ok
Market -> SmartMeter ++: returnReservedBatteryCharge\n\t\t (address, amount)
SmartMeter --> Market --: OK
else
Market -> Events: emit new contract(pendingOffer[i])
end
end
Market -> DSO --: OK

@enduml