@startuml BuyOffer
actor DSO
participant Market #LightYellow
participant SmartMeter #LightYellow
participant Events #LightYellow 

skinparam dpi 300

autonumber

DSO -> Market++: getPendingOffers
Market --> DSO: pendingOffers
DSO -> Market: validateOffers(pendingOffers)
loop pendingOffers
alt pendingOffer[i] == true
Market -> Events: emit new contract(pendingOffer[i])
Events --> Market: ok
else pendingOffer[i] == false
Market -> SmartMeter ++: returnReservedBatteryCharge(address, amount)
SmartMeter --> Market --: ok
end
end
Market --> DSO: offers validated
@enduml