@startuml BuyOffer
actor DSO
participant GroupSignature
participant Market #LightYellow
participant SmartMeter #LightYellow
participant Events #LightYellow 

skinparam dpi 300

autonumber

DSO -> Market: getPendingOffers
Market --> DSO: pendingOffers
DSO -> Market: validateOffers(indicies)
loop indicies
alt indicies[i] = false
Market -> SmartMeter ++: returnReservedBatteryCharge(address, amount)
SmartMeter --> Market --: OK
else
Market -> Events: emit new contract(pendingOffer[i])
end
end

@enduml