@startuml withdraw battery
start
:subtractBatteryCharge(amount, ots, nextOtsHash);
if (is caller == Market) then (true)
    if (hash(ots) == otsHash) then (true)
    :set otsHash = nextHash;
        if (batteryCharge >= amount) then (true)
            :set charge -= amount;
            :validation = true;
        else (false)
        endif
    
    else (false)
    endif
else (false)
endif
stop
@enduml