@startuml AddOffer
actor User
participant SmartMeter
participant Market
participant CableCompany

skinparam responseMessageBelowArrow true

group Before
    note over SmartMeter: Logs usage
    SmartMeter -> SmartMeter: createLog()

    SmartMeter -> SmartMeter: setBatteryCharge()
end group

autonumber
User -> Market ++: addOffer(offer)

Market -> CableCompany ++: isRegistered(user.smartMeter)
CableCompany --> Market --: SmartMeter registered

Market -> SmartMeter ++: check batteryLevel()
SmartMeter --> Market --: batteryLevel OK

Market -> Market: createOffer

Market --> User: Offer created!
@enduml
