@startuml AddOffer
actor Prosumer
participant SmartMeter #LightYellow
participant GroupSignature
participant Market #LightYellow
participant CableCompany #LightYellow

skinparam dpi 400

group Before
    note over SmartMeter: Logs usage
    SmartMeter -> SmartMeter: createLog()

    SmartMeter -> SmartMeter: setBatteryCharge()
end group

autonumber

Prosumer -> GroupSignature ++: sign(offer, nonce)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: addOffer(offer, signature, nonce)

Market -> CableCompany ++: isRegistered(smartMeter)
CableCompany --> Market --: SmartMeter registered

Market -> SmartMeter ++: check batteryLevel()
SmartMeter --> Market --: batteryLevel OK

Market -> Market: createOffer

Market --> Prosumer: Offer created!
@enduml
