@startuml AddOffer
actor Prosumer
participant SmartMeter #LightYellow
participant GroupSignature
participant Market #LightYellow
participant CableCompany #LightYellow

group Before
    note over SmartMeter: Logs usage
    SmartMeter -> SmartMeter: createLog()

    SmartMeter -> SmartMeter: setBatteryCharge()
end group

autonumber
Prosumer -> Market ++: addOffer(offer, ots, nextOtsHash, nonce)
Market -> Market: verifyNonce(nonce)

Market -> CableCompany ++: isRegistered(prosumer.smartMeter)
CableCompany --> Market --: SmartMeter registered

Market -> SmartMeter ++: check batteryLevel(ots, nextOtsHash, amount)
SmartMeter -> SmartMeter: verifyAndSetNextOTS(ots, nextOtsHash)
SmartMeter -> SmartMeter: subtractBattery(amount)
SmartMeter --> Market --: batteryLevel OK

Market -> Market: createOffer

Market --> Prosumer: Offer created!
@enduml
