@startuml BuyOffer
actor Prosumer
participant GroupSignature
participant Market #LightYellow
participant SupplyContract #LightYellow

skinparam dpi 300

autonumber

Prosumer -> GroupSignature ++: sign(offer)
GroupSignature --> Prosumer --: signature

Prosumer -> Market ++: buyOffer(id, signature)
Market -> Market: Check validity
note over Market #WhiteSmoke
expiration > now
owner != buyer
end note

Market -> SupplyContract ++: Deploy new SupplyContract
SupplyContract --> Market --:

Market --> Prosumer: SupplyContract created!
@enduml