name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./client
        steps:
            - uses: actions/checkout@v3

            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.npm
                      ./client/node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('./client/package-lock.json') }}

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - name: Install dependencies, build, and lint
              run: npm install
              run: npm run build --if-present
              run: npm run lint

            - name: Install Truffle
              run: npm install truffle@5.4.29 -g
              run: npm install

            - name: Run Truffle in the background
              run: truffle develop --log &

            - name: Run Truffle tests
              run: CI=true truffle test --network ci
